name: Mirror to GitHub
on: [push]

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Push to GitHub
        run: |
          git clone --bare ${{ github.server_url }}/${{ github.repository }}.git repo
          cd repo
          git push --mirror https://${{ secrets.USER_GITHUB }}:${{ secrets.PAT_GITHUB }}@github.com/${{ secrets.USER_GITHUB }}/${{ github.event.repository.name }}.git