name: Test

on:
  pull_request:
    branches:
      - main
    paths:
      - 'src/**.jl'
      - 'test/**.jl'
  push:
    tags:
      - 'v*'

concurrency:
  # cancels when a PR gets updated
  group: ${{ forgejo.head_ref || forgejo.run_id }}-${{ forgejo.actor }}
  cancel-in-progress: true

jobs:
  test:
    name: Julia ${{ matrix.version }} - ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        julia-version: ['1.12']
        os: [debian]

    steps:
      - uses: actions/checkout@v6
      - uses: https://github.com/julia-actions/setup-julia@v2
        with:
          version: ${{ matrix.julia-version }}
      - run: julia -e 'import Pkg; Pkg.Registry.add(Pkg.RegistrySpec(url="https://github.com/astro-group-bristol/AstroRegistry/"))'
      - uses: https://github.com/julia-actions/julia-buildpkg@v1
      - uses: https://github.com/julia-actions/julia-runtest@v1
      - uses: https://github.com/julia-actions/julia-processcoverage@v1
        with:
          directories: src
